spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.locations=classpath:db/migration,classpath:db/migration/postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.validate-on-migrate=true
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-seconds=${SECURITY_JWT_EXPIRATION_SECONDS}
security.jwt.issuer=${SECURITY_JWT_ISSUER}
