spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-seconds=${SECURITY_JWT_EXPIRATION_SECONDS}
security.jwt.issuer=${SECURITY_JWT_ISSUER}
