spring.application.name=Przepisnik
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.h2.console.enabled=false
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-seconds=${SECURITY_JWT_EXPIRATION_SECONDS:3600}
security.jwt.issuer=${SECURITY_JWT_ISSUER:Przepisnik}
