const constants = {
    titleApp: 'Przepi\u015Bnik',
    home: {
        title: 'Odkryj przepisy',
        subtitle: 'Przegl\u0105daj publiczne przepisy kulinarne naszej spo\u0142eczno\u015Bci.',
        searchPlaceholder: 'Szukaj przepis\u00F3w\u2026',
        searchButton: 'Szukaj',
        clearButton: 'Wyczy\u015B\u0107',
        loading: '\u0141adowanie przepis\u00F3w\u2026',
        empty: 'Nie znaleziono \u017Cadnych publicznych przepis\u00F3w.',
        emptySearch: 'Brak wynik\u00F3w dla podanej frazy.',
        loadError: 'Nie uda\u0142o si\u0119 za\u0142adowa\u0107 przepis\u00F3w.',
        authorPrefix: 'Autor:',
    },
    footer: {
        rightsText: '\u00A9 2025 Przepi\u015Bnik. All rights reserved.',
    },
    dashboardUser:
    {
        welcomeText: 'Witaj szefie!',
    },
    layout: {
        header: {
            logout: 'Wyloguj',
            addRecipe: '+ Przepis',
            ingredients: 'Składniki',
            login: 'Zaloguj',
            register: 'Zarejestruj',
            welcomePrefix: 'Witaj,',
        },
    },
    routes: {
        home: '/',
        login: '/login',
        register: '/register',
        myRecipes: '/my-recipes',
        recipeNew: '/recipes/new',
        recipeEdit: '/recipes/:id/edit',
        ingredients: '/ingredients',
        notFoundText: '404 - Strona nie istnieje',
    },
    auth: {
        login: {
            title: 'Zaloguj si\u0119',
            emailLabel: 'Email',
            passwordLabel: 'Haslo',
            missingCredentials: 'Email i haslo sa wymagane.',
            shortPassword: 'Haslo musi miec minimum 4 znaki.',
            submit: 'Zaloguj',
            submitting: 'Logowanie...',
            noAccount: 'Nie masz konta?',
            registerCta: 'Zarejestruj si\u0119',
        },
        register: {
            title: 'Zarejestruj si\u0119',
            emailLabel: 'Email',
            passwordLabel: 'Haslo',
            nameLabel: 'Imie',
            surnameLabel: 'Nazwisko',
            missingRequired: 'Email, haslo i imie sa wymagane.',
            invalidEmail: 'Podaj poprawny adres email.',
            shortPassword: 'Haslo musi miec minimum 4 znaki.',
            submit: 'Zarejestruj',
            submitting: 'Rejestracja...',
            hasAccount: 'Masz ju\u017C konto?',
            loginCta: 'Zaloguj si\u0119',
            successTitle: 'Konto utworzone',
            successMessage: 'Rejestracja zako\u0144czy\u0142a si\u0119 sukcesem. Przejd\u017A do logowania, aby zalogowa\u0107 si\u0119 na nowe konto.',
            successConfirmLabel: 'Przejd\u017A do logowania',
        },
        generic: {
            unexpectedError: 'Wystapil nieoczekiwany blad.',
            serverIssue: 'Wykryto problem z serwerem. Sprawdz polaczenie z backendem i sprobuj ponownie.',
            providerUsageError: 'useAuth must be used within AuthProvider.',
        },
    },
    recipes: {
        list: {
            title: 'Moje przepisy',
            addButton: '+ Dodaj przepis',
            loading: 'Ładowanie...',
            empty: 'Nie masz jeszcze żadnych przepisów.',
            addFirstButton: 'Dodaj pierwszy przepis',
            deleteDialogTitle: 'Usunąć przepis?',
            deleteDialogMessageWithName: 'Czy na pewno usunąć przepis "{name}"? Tej operacji nie można cofnąć.',
            deleteDialogMessageGeneric: 'Czy na pewno usunąć ten przepis? Tej operacji nie można cofnąć.',
            deleting: 'Usuwanie...',
            deleteConfirm: 'Usuń',
            loadError: 'Nie udało się załadować przepisów.',
            deleteError: 'Nie udało się usunąć przepisu.',
            timeSuffix: 'min',
            servingsSuffix: 'porcji',
            ingredientsLabel: 'Składniki:',
            createdPrefix: 'Utworzony:',
            editButton: 'Edytuj',
            deleteButton: 'Usuń',
            dateLocale: 'pl-PL',
        },
        formPage: {
            loading: 'Ładowanie...',
            editTitle: 'Edytuj przepis',
            createTitle: 'Dodaj nowy przepis',
            loadError: 'Nie udało się załadować przepisu.',
        },
        form: {
            labels: {
                name: 'Nazwa przepisu *',
                preparationTime: 'Czas przygotowania (min) *',
                servings: 'Liczba porcji *',
                privacy: 'Prywatność przepisu',
                ingredients: 'Składniki *',
                description: 'Opis przygotowania *',
            },
            placeholders: {
                name: 'np. Nalesniki',
                preparationTime: '20',
                servings: '4',
                ingredientName: 'Nazwa składnika',
                ingredientQuantity: 'Ilość',
                description: 'Opisz kroki przygotowania potrawy',
            },
            buttons: {
                addIngredient: '+ Dodaj składnik',
                save: 'Zapisz',
                saveChanges: 'Zapisz zmiany',
                saving: 'Zapisywanie...',
            },
            errors: {
                requiredField: 'To pole jest wymagane.',
                minValuePrefix: 'Wartosc musi byc co najmniej',
                nameRequired: 'Nazwa przepisu jest wymagana.',
                descriptionRequired: 'Opis przygotowania jest wymagany.',
                prepTimeInvalid: 'Czas przygotowania musi być liczbą większą od 0.',
                servingsInvalid: 'Liczba porcji musi być liczbą większą od 0.',
                ingredientRequired: 'Dodaj co najmniej jeden składnik.',
                ingredientUnique: 'Nazwy składników muszą być unikalne.',
                ingredientFixHint: 'Popraw pola składników oznaczone na czerwono.',
                ingredientQuantityRequired: 'Ilosc skladnika jest wymagana.',
                ingredientQuantityMin: 'Ilosc skladnika musi byc co najmniej 0.01.',
                ingredientNameRequired: 'Nazwa skladnika jest wymagana.',
                submitFallback: 'Coś poszło nie tak. Spróbuj ponownie.',
            },
            units: {
                GRAM: 'g',
                KG: 'kg',
                ML: 'ml',
                L: 'l',
                PIECE: 'szt.',
                TABLESPOON: 'łyżka',
                TEASPOON: 'łyżeczka',
                CUP: 'szklanka',
            },
            privacyOptions: {
                public: 'Publiczny',
                private: 'Prywatny',
            },
        },
    },
    ingredients: {
        list: {
            title: 'Składniki',
            addButton: '+ Dodaj składnik',
            loading: 'Ładowanie...',
            empty: 'Nie znaleziono żadnych składników.',
            emptySearch: 'Brak wyników dla podanej frazy.',
            loadError: 'Nie udało się załadować składników.',
            searchPlaceholder: 'Szukaj składników...',
            searchButton: 'Szukaj',
            clearButton: 'Wyczyść',
            editButton: 'Edytuj',
            deleteButton: 'Usuń',
            deleteDialogTitle: 'Usunąć składnik?',
            deleteDialogMessage: 'Czy na pewno usunąć składnik "{name}"? Tej operacji nie można cofnąć.',
            deleting: 'Usuwanie...',
            deleteConfirm: 'Usuń',
            deleteError: 'Nie udało się usunąć składnika.',
            btw: 'Zawartość w 100g/100mL',
            ingredientColumn: 'Składnik',
            actionsColumn: 'Akcje',
            protein: 'Białko',
            fat: 'Tłuszcz',
            carbohydrates: 'Węglowodany',
            noData: '-',
            paginationPrev: 'Poprzednia',
            paginationNext: 'Następna',
            paginationOf: 'z',
        },
        form: {
            title: 'Dodaj składnik',
            editTitle: 'Edytuj składnik',
            labels: {
                name: 'Nazwa *',
                protein: 'Białko (g) *',
                fat: 'Tłuszcz (g) *',
                carbohydrates: 'Węglowodany (g) *',
            },
            placeholders: {
                name: 'np. Mąka pszenna',
                protein: '10',
                fat: '2',
                carbohydrates: '75',
            },
            buttons: {
                save: 'Zapisz',
                saving: 'Zapisywanie...',
                cancel: 'Anuluj',
            },
            errors: {
                requiredField: 'To pole jest wymagane.',
                nameRequired: 'Nazwa składnika jest wymagana.',
                proteinInvalid: 'Białko musi być liczbą z maksymalnie 2 miejscami po przecinku.',
                fatInvalid: 'Tłuszcz musi być liczbą z maksymalnie 2 miejscami po przecinku.',
                carbohydratesInvalid: 'Węglowodany muszą być liczbą z maksymalnie 2 miejscami po przecinku.',
                submitFallback: 'Coś poszło nie tak. Spróbuj ponownie.',
                alreadyExists: 'Składnik o tej nazwie już istnieje.',
            },
        },
    },
    shared: {
        sessionCheck: 'Sprawdzanie sesji...',
    },
    api: {
        headers: {
            contentType: 'Content-Type',
            contentTypeValue: 'application/json',
            authorization: 'Authorization',
            bearerPrefix: 'Bearer ',
        },
        auth: {
            login: '/api/auth/login',
            usersCreate: '/api/users/create',
            usersMe: '/api/users/me',
            roleUser: 'USER',
        },
        recipes: {
            create: '/api/recipes/create',
            my: '/api/recipes/my',
            public: '/api/recipes/public',
            byId: (id: string) => `/api/recipes/${id}`,
            update: (id: string) => `/api/recipes/update/${id}`,
            delete: (id: string) => `/api/recipes/delete/${id}`,
        },
        ingredients: {
            list: '/api/ingredients/list',
            create: '/api/ingredients/create',
            byId: (id: string) => `/api/ingredients/${id}`,
            update: (id: string) => `/api/ingredients/update/${id}`,
            delete: (id: string) => `/api/ingredients/delete/${id}`,
        },
        errors: {
            noApiConnection: 'Nie mozna polaczyc z API. Sprawdz czy backend dziala i czy frontend ma poprawna konfiguracje proxy.',
            unauthorizedConfig: 'Serwer odrzucil zapytanie. Sprawdz konfiguracje bezpieczenstwa backendu i sprobuj ponownie.',
            serverUnavailable: 'Serwer jest chwilowo niedostepny. Sprobuj ponownie za moment.',
            requestFailed: 'Nie udalo sie wykonac zadania. Sprobuj ponownie.',
            noServerConnection: 'Nie mozna polaczyc z serwerem. Upewnij sie, ze backend jest uruchomiony.',
            missingPayload: 'Missing response payload.',
        },
    },
};

export default constants;
