const constants = {
    titleApp: 'Przepi\u015Bnik',
    home: {
        title: 'Home Page',
    },
    footer: {
        rightsText: '\u00A9 2025 Przepi\u015Bnik. All rights reserved.',
    },
    dashboardUser:
    {
        welcomeText: 'Witaj szefie!',
    },
    layout: {
        header: {
            logout: 'Wyloguj',
            addRecipe: '+ Przepis',
        },
    },
    routes: {
        home: '/',
        login: '/login',
        register: '/register',
        myRecipes: '/my-recipes',
        recipeNew: '/recipes/new',
        recipeEdit: '/recipes/:id/edit',
        notFoundText: '404 - Strona nie istnieje',
    },
    auth: {
        login: {
            title: 'Zaloguj si\u0119',
            emailLabel: 'Email',
            passwordLabel: 'Haslo',
            missingCredentials: 'Email i haslo sa wymagane.',
            shortPassword: 'Haslo musi miec minimum 4 znaki.',
            submit: 'Zaloguj',
            submitting: 'Logowanie...',
            noAccount: 'Nie masz konta?',
            registerCta: 'Zarejestruj si\u0119',
        },
        register: {
            title: 'Zarejestruj si\u0119',
            emailLabel: 'Email',
            passwordLabel: 'Haslo',
            nameLabel: 'Imie',
            surnameLabel: 'Nazwisko',
            missingRequired: 'Email, haslo i imie sa wymagane.',
            invalidEmail: 'Podaj poprawny adres email.',
            shortPassword: 'Haslo musi miec minimum 4 znaki.',
            submit: 'Zarejestruj',
            submitting: 'Rejestracja...',
            hasAccount: 'Masz ju\u017C konto?',
            loginCta: 'Zaloguj si\u0119',
            successTitle: 'Konto utworzone',
            successMessage: 'Rejestracja zako\u0144czy\u0142a si\u0119 sukcesem. Przejd\u017A do logowania, aby zalogowa\u0107 si\u0119 na nowe konto.',
            successConfirmLabel: 'Przejd\u017A do logowania',
        },
        generic: {
            unexpectedError: 'Wystapil nieoczekiwany blad.',
            serverIssue: 'Wykryto problem z serwerem. Sprawdz polaczenie z backendem i sprobuj ponownie.',
            providerUsageError: 'useAuth must be used within AuthProvider.',
        },
    },
    recipes: {
        list: {
            title: 'Moje przepisy',
            addButton: '+ Dodaj przepis',
            loading: '\u0141adowanie...',
            empty: 'Nie masz jeszcze \u017Cadnych przepis\u00F3w.',
            addFirstButton: 'Dodaj pierwszy przepis',
            deleteDialogTitle: 'Usun\u0105\u0107 przepis?',
            deleteDialogMessageWithName: 'Czy na pewno usun\u0105\u0107 przepis "{name}"? Tej operacji nie mo\u017Cna cofn\u0105\u0107.',
            deleteDialogMessageGeneric: 'Czy na pewno usun\u0105\u0107 ten przepis? Tej operacji nie mo\u017Cna cofn\u0105\u0107.',
            deleting: 'Usuwanie...',
            deleteConfirm: 'Usu\u0144',
            loadError: 'Nie uda\u0142o si\u0119 za\u0142adowa\u0107 przepis\u00F3w.',
            deleteError: 'Nie uda\u0142o si\u0119 usun\u0105\u0107 przepisu.',
            timeSuffix: 'min',
            servingsSuffix: 'porcji',
            ingredientsLabel: 'Sk\u0142adniki:',
            createdPrefix: 'Utworzony:',
            editButton: 'Edytuj',
            deleteButton: 'Usu\u0144',
            dateLocale: 'pl-PL',
        },
        formPage: {
            loading: '\u0141adowanie...',
            editTitle: 'Edytuj przepis',
            createTitle: 'Dodaj nowy przepis',
            loadError: 'Nie uda\u0142o si\u0119 za\u0142adowa\u0107 przepisu.',
        },
        form: {
            labels: {
                name: 'Nazwa przepisu *',
                preparationTime: 'Czas przygotowania (min) *',
                servings: 'Liczba porcji *',
                ingredients: 'Sk\u0142adniki *',
                description: 'Opis przygotowania *',
            },
            placeholders: {
                name: 'np. Nalesniki',
                preparationTime: '20',
                servings: '4',
                ingredientName: 'Nazwa sk\u0142adnika',
                ingredientQuantity: 'Ilo\u015B\u0107',
                description: 'Opisz kroki przygotowania potrawy',
            },
            buttons: {
                addIngredient: '+ Dodaj sk\u0142adnik',
                save: 'Zapisz',
                saveChanges: 'Zapisz zmiany',
                saving: 'Zapisywanie...',
            },
            errors: {
                requiredField: 'To pole jest wymagane.',
                minValuePrefix: 'Wartosc musi byc co najmniej',
                nameRequired: 'Nazwa przepisu jest wymagana.',
                descriptionRequired: 'Opis przygotowania jest wymagany.',
                prepTimeInvalid: 'Czas przygotowania musi by\u0107 liczb\u0105 wi\u0119ksz\u0105 od 0.',
                servingsInvalid: 'Liczba porcji musi by\u0107 liczb\u0105 wi\u0119ksz\u0105 od 0.',
                ingredientRequired: 'Dodaj co najmniej jeden sk\u0142adnik.',
                ingredientUnique: 'Nazwy sk\u0142adnik\u00F3w musz\u0105 by\u0107 unikalne.',
                ingredientFixHint: 'Popraw pola sk\u0142adnik\u00F3w oznaczone na czerwono.',
                ingredientQuantityRequired: 'Ilosc skladnika jest wymagana.',
                ingredientQuantityMin: 'Ilosc skladnika musi byc co najmniej 0.01.',
                ingredientNameRequired: 'Nazwa skladnika jest wymagana.',
                submitFallback: 'Co\u015B posz\u0142o nie tak. Spr\u00F3buj ponownie.',
            },
            units: {
                GRAM: 'gram',
                KG: 'kg',
                ML: 'ml',
                L: 'l',
                PIECE: 'szt.',
                TABLESPOON: '\u0142y\u017Cka',
                TEASPOON: '\u0142y\u017Ceczka',
                CUP: 'szklanka',
            },
        },
    },
    shared: {
        sessionCheck: 'Sprawdzanie sesji...',
    },
    api: {
        headers: {
            contentType: 'Content-Type',
            contentTypeValue: 'application/json',
            authorization: 'Authorization',
            bearerPrefix: 'Bearer ',
        },
        auth: {
            login: '/api/auth/login',
            usersCreate: '/api/users/create',
            usersMe: '/api/users/me',
            roleUser: 'USER',
        },
        recipes: {
            create: '/api/recipes/create',
            my: '/api/recipes/my',
            byId: (id: string) => `/api/recipes/${id}`,
            update: (id: string) => `/api/recipes/update/${id}`,
            delete: (id: string) => `/api/recipes/delete/${id}`,
        },
        errors: {
            noApiConnection: 'Nie mozna polaczyc z API. Sprawdz czy backend dziala i czy frontend ma poprawna konfiguracje proxy.',
            unauthorizedConfig: 'Serwer odrzucil zapytanie. Sprawdz konfiguracje bezpieczenstwa backendu i sprobuj ponownie.',
            serverUnavailable: 'Serwer jest chwilowo niedostepny. Sprobuj ponownie za moment.',
            requestFailed: 'Nie udalo sie wykonac zadania. Sprobuj ponownie.',
            noServerConnection: 'Nie mozna polaczyc z serwerem. Upewnij sie, ze backend jest uruchomiony.',
            missingPayload: 'Missing response payload.',
        },
    },
};

export default constants;
